############################################################
# top level directories
sourcedir: /work/project/ext_016/outputs
refdir: /work/project/ext_016
############################################################
# reference files, genome indices and data
reference:
  stargenomedir:
    hg38: $refdir

  fasta:
    hg38: $refdir/GRCh37_latest_genomic.fna

  gtf:
    hg38: $refdir/gencode.v19.annotation.gtf
  
  1000G:
    hg38: $refdir/1000G_phase1.indels.b37.vcf
  
  Indels:
    hg38: $refdir/Mills_and_1000G_gold_standard.indels.hg19.sites.vcf
  
  DbSNP:
    hg38: $refdir/GRCh37_latest_dbSNP_all.vcf


  star_ref: "/work/project/ext_016"


# directory structure for input and output files

datadirs:
  fastq: $sourcedir/demo_data
  qc: $sourcedir/qc_output
  trim: $sourcedir/trimmed_files
  bam: $sourcedir/pass1
  sj_files: $sourcedir/sj_files
  pass2: $sourcedir/pass2
  RGbam: $sourcedir/RGbam
  dedup: $sourcedir/dedup
  splitNcigar: $sourcedir/splitNcigar
  Recal1: $sourcedir/Recal1
  BQSR_1: $sourcedir/BQSR_1
  Recal2: $sourcedir/Recal2
  BQSR_2: $sourcedir/BQSR_2
  vcf: sourcedir/vcf
  CombinedGvcfs: $sourcedir/CombinedGvcfs

